
#######################################################################
# +-----------------------------------------------------------------+ #
# |                           WorldConfig                           | #
# +-----------------------------------------------------------------+ #
#######################################################################

Author: Shivaxi & NLBlackEagle

Description: Special RLCraft Dregora addition, does not work without the RLCraft Dregora modpack.

WorldPackerModName: Underneath

Version: 1.8

SettingsMode: WriteDisable


#######################################################################
# +-----------------------------------------------------------------+ #
# |                            The modes                            | #
# +-----------------------------------------------------------------+ #
#######################################################################

TerrainMode: Normal

BiomeMode: FromImage


#######################################################################
# +-----------------------------------------------------------------+ #
# |                          Custom biomes                          | #
# +-----------------------------------------------------------------+ #
#######################################################################

CustomBiomes: 

#######################################################################
# +-----------------------------------------------------------------+ #
# |                  Settings for BiomeMode: Normal                 | #
# +-----------------------------------------------------------------+ #
#######################################################################

GenerationDepth: 9

BiomeRarityScale: 100

################
# Biome Groups #
################

BiomeGroup(Resource Caverns, 0, 90,  Underspikes, Underforest, Defiled Caverns)
BiomeGroup(Mild Caverns, 0, 100,  Underneath)
BiomeGroup(Deadly Caverns, 4, 95,  Corrupted)


###############
# Biome lists #
###############

IsleBiomes: Underneath Pillar, Underneath Hole, Corrupted Pillar, Underspikes Pillar

BorderBiomes: Underneath Edge, Corrupted Edge, Underspikes Edge

CustomHeightControlSmoothing: true

ImprovedSmoothing: true

ImprovedBiomeBorders: true

ImprovedBiomeGroups: true


########################################
# Landmass settings (for NormalBiomes) #
########################################

LandRarity: 100

LandSize: 0

LandFuzzy: 8

DefaultOceanBiome: Underneath

#####################
# Ice area settings #
#####################

FrozenOcean: false

OceanFreezingTemperature: 0.15

FreezeAllBiomesInColdGroup: false

DefaultFrozenOceanBiome: FrozenOcean

##########
# Rivers #
##########

RiverRarity: 1

RiverSize: 2

RiversEnabled: true

ImprovedRivers: false

RandomRivers: true


#######################################################################
# +-----------------------------------------------------------------+ #
# |                 Settings for BiomeMode:FromImage                | #
# +-----------------------------------------------------------------+ #
#######################################################################

ImageMode: ContinueNormal

ImageFile: map.png

ImageOrientation: North

ImageFillBiome: 

ImageXOffset: -1500

ImageZOffset: -1500


#######################################################################
# +-----------------------------------------------------------------+ #
# |                  Terrain height and volatility                  | #
# +-----------------------------------------------------------------+ #
#######################################################################

WorldHeightScaleBits: 8

WorldHeightCapBits: 8

FractureHorizontal: 1.1

FractureVertical: -2.0


#######################################################################
# +-----------------------------------------------------------------+ #
# |                              Blocks                             | #
# +-----------------------------------------------------------------+ #
#######################################################################

RemoveSurfaceStone: false

DisableBedrock: false

CeilingBedrock: false

FlatBedrock: false

BedrockBlock: BEDROCK

PopulationBoundsCheck: false


################################
# Water / Lava & Frozen States #
################################

WaterLevelMax: 63

WaterLevelMin: 0

WaterBlock: BIOMESOPLENTY:BLOOD

IceBlock: BIOMESOPLENTY:FLESH

CooledLavaBlock: OBSIDIAN

##############
# World only #
##############

FullyFreezeLakes: true

UseTemperatureForSnowHeight: true

BetterSnowFall: false


#######################################################################
# +-----------------------------------------------------------------+ #
# |                            Resources                            | #
# +-----------------------------------------------------------------+ #
#######################################################################

ResourcesSeed: 0


#######################################################################
# +-----------------------------------------------------------------+ #
# |                            Structures                           | #
# +-----------------------------------------------------------------+ #
#######################################################################

###############
# Strongholds #
###############

StrongholdsEnabled: false

StrongholdCount: 128

StrongholdDistance: 32.0

StrongholdSpread: 3

############
# Villages #
############

VillagesEnabled: false

VillageSize: 0

VillageDistance: 32

##################
# Rare buildings #
##################

RareBuildingsEnabled: false

MinimumDistanceBetweenRareBuildings: 9

MaximumDistanceBetweenRareBuildings: 32

#####################
# Woodland Mansions #
#####################

WoodLandMansionsEnabled: false

###################
# Ocean monuments #
###################

OceanMonumentsEnabled: false

OceanMonumentGridSize: 32

OceanMonumentRandomOffset: 26

#################################
# Custom structures and objects #
#################################

IsOTGPlus: true

ReplaceBlocksList: []

MaximumCustomStructureRadius: 25

####################
# Other structures #
####################

MineshaftsEnabled: false

NetherFortressesEnabled: false


#######################################################################
# +-----------------------------------------------------------------+ #
# |                         Visual settings                         | #
# +-----------------------------------------------------------------+ #
#######################################################################

WorldFog: #FFFFFF

WorldNightFog: #0B0D17


#######################################################################
# +-----------------------------------------------------------------+ #
# |                          Cave settings                          | #
# +-----------------------------------------------------------------+ #
#######################################################################

CaveRarity: 7

CaveFrequency: 40

CaveMinAltitude: 8

CaveMaxAltitude: 255

IndividualCaveRarity: 25

CaveSystemFrequency: 1

CaveSystemPocketChance: 0

CaveSystemPocketMinSize: 0

CaveSystemPocketMaxSize: 3

EvenCaveDistrubution: false


#######################################################################
# +-----------------------------------------------------------------+ #
# |                         Ravine settings                         | #
# +-----------------------------------------------------------------+ #
#######################################################################

RavineRarity: 0

RavineMinAltitude: 245

RavineMaxAltitude: 255

RavineMinLength: 84

RavineMaxLength: 588

RavineDepth: 2.4


#######################################################################
# +-----------------------------------------------------------------+ #
# |                            World Seed                           | #
# +-----------------------------------------------------------------+ #
#######################################################################

WorldSeed:


#######################################################################
# +-----------------------------------------------------------------+ #
# |                           BO3 at spawn                          | #
# +-----------------------------------------------------------------+ #
#######################################################################

BO3AtSpawn:


#######################################################################
# +-----------------------------------------------------------------+ #
# |                      Pre-generation radius                      | #
# +-----------------------------------------------------------------+ #
#######################################################################

PreGenerationRadius: 0


#######################################################################
# +-----------------------------------------------------------------+ #
# |                       World border radius                       | #
# +-----------------------------------------------------------------+ #
#######################################################################

WorldBorderRadius: 0


#######################################################################
# +-----------------------------------------------------------------+ #
# |                            Dimension                            | #
# +-----------------------------------------------------------------+ #
#######################################################################

Dimensions: Underneath

DimensionBelow: Underneath

DimensionAbove: 

DimensionBelowHeight: 0

DimensionAboveHeight: 256

DimensionPortalMaterials: srparasites:parasitestain, srparasites:parasiterubbledense:1, srparasites:parasitestain:1

TeleportToSpawnOnly: true

Cartographer: false

PortalColor: darkred

PortalParticleType: townaura

PortalMobType:

PortalMobSpawnChance: 0

TeleportToSpawnOnly: false

##############
# Game rules #
##############

CommandBlockOutput: true

DisableElytraMovementCheck: true

DoDaylightCycle: false

DoEntityDrops: true

DoFireTick: true

DoLimitedCrafting: false

DoMobLoot: true

DoMobSpawning: true

DoTileDrops: true

DoWeatherCycle: false

GameLoopFunction: true

KeepInventory: false

LogAdminCommands: true

MaxCommandChainLength: 65536

MaxEntityCramming: 24

MobGriefing: true

NaturalRegeneration: true

RandomTickSpeed: 3

ReducedDebugInfo: false

SendCommandFeedback: true

ShowDeathMessages: true

SpawnRadius: 5000

SpectatorsGenerateChunks: true

###########################
# World provider settings #
###########################

WelcomeMessage: 

DepartMessage: 

HasSkyLight: false

IsSurfaceWorld: false

CanRespawnHere: true

DoesWaterVaporize: false

DoesXZShowFog: false

UseCustomFogColor: true

FogColorRed: 0.4

FogColorGreen: 0.08

FogColorBlue: 0.08

IsSkyColored: true

CloudHeight: 500

CanDoLightning: true

CanDoRainSnowIce: true

IsNightWorld: true

VoidFogYFactor: 0.8

GravityFactor: 0.07

ShouldMapSpin: false

CanDropChunk: true

RespawnDimension: 3

MovementFactor: 1

ItemsToAddOnJoinDimension: 

ItemsToRemoveOnJoinDimension: 

ItemsToAddOnLeaveDimension: 

ItemsToRemoveOnLeaveDimension: 

ItemsToAddOnRespawn: 

SpawnPointSet: true

SpawnPointX: 0

SpawnPointY: 260

SpawnPointZ: 0

PlayersCanBreakBlocks: true

ExplosionsCanBreakBlocks: true

PlayersCanPlaceBlocks: true

